# Generated by Django 3.1.6 on 2021-02-23 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('acarajeapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SemAlcool',
            new_name='Cardapio',
        ),
        migrations.DeleteModel(
            name='Acaraje',
        ),
        migrations.DeleteModel(
            name='Cervejas',
        ),
        migrations.DeleteModel(
            name='Destilados',
        ),
        migrations.DeleteModel(
            name='Porcoes',
        ),
    ]
